[32mINFO    [0m root:test_time_series_daily.py:75 test_time_series_daily_invalid_symbol started
[32mINFO    [0m root:test_time_series_daily.py:79 response : {
    "Error Message": "Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_DAILY."
}
[32mINFO    [0m root:test_time_series_daily.py:84 test_time_series_daily_invalid_symbol ended